### ISSUE TITLE
Division Documentation Tasks For Second Deliverable

### ISSUE THREAD

**Issue by adrian-demig-pal** [Arquisoft/Agents_i3b#2]
In order to divide the work, I can find 2 different tasks:

- Correct the previous documentation from the first delivarable. (This task can be done by only one member)

- Create the new documentation for the new module. (This task can be done between two members)

Comment anything if you don´t agree.

**Comment by adrian-demig-pal** [comment]
I would like to correct the previous documentation due to I took some notes during the correction in order to do it.

**Comment by Victorreme** [comment]
The distribtion has been made durig the meeting.
Adrian will do the correction.
Alfredo and Victor will create the new documentation.
