### ISSUE TITLE
Create new documentation

### ISSUE THREAD

**Issue by Victorreme** [Arquisoft/Agents_i3b#4]
Victor:
- [x] Introduction and goals
- [x] Requirements
- [x] Architecture constraints
- [x] Context view
- [x] InciDashboard view

Alfredo:

- [x] Stakeholders
- [x] Quality Atributes
- [x] System scope and context
- [x] Quality scenarios (victor review)

**Comment by Victorreme** [comment]
Requirements done

**Comment by alfredofuentes9** [comment]
- Stakeholders 
- Quality Atributtes
- System scope and context
- Quality scenarios (victor review)

**Comment by alfredofuentes9** [comment]
Stakeholders done

**Comment by alfredofuentes9** [comment]
quality atributes updated but not finished

**Comment by alfredofuentes9** [comment]
QA finished

**Comment by alfredofuentes9** [comment]
ssc finished in vp

**Comment by alfredofuentes9** [comment]
Ssc and qs finished

**Comment by alfredofuentes9** [comment]
ssc updated

**Comment by Victorreme** [comment]
Context view updated.
InciDashboard view updated and mostly finished.

**Comment by Victorreme** [comment]
InciDashboard view finished

**Comment by alfredofuentes9** [comment]
ssc upgraded

**Comment by Victorreme** [comment]
Context view finished
